#! /usr/bin/env node --experimental-fetch  --no-warnings

const {DEBUG, NODE_ENV} = process.env;
const {scraper} = require('../lib/scraper');

scraper('https://www.chicago.gov/city/en/about/wards.html');
